### ISSUE TITLE
cljr-clean-ns doesn't account for namespaced keywords

### ISSUE THREAD

**Issue by julienfantin** [clojure-emacs/refactor-nrepl#175]
## Expected behavior

Calling `cljr-clean-ns` should preserve namespaces used only in keyword aliases.

```clojure
(ns my.foo
  (:require
   [clojure.spec :as s]
   [my.bar :as bar]))

(s/def ::config (s/keys :req-un [::bar/baz]))
```
## Actual behavior

The aliased namespace is removed if not used for a symbol reference. 

`clojure.spec` accepts the un-required alias as a valid spec, but the intended spec is never loaded, which will cause a runtime error

```clojure
(ns my.foo
  (:require
   [clojure.spec :as s]))

(s/def ::config (s/keys :req-un [::bar/baz]))
```
## Steps to reproduce the problem

`src/my/bar.clj`
```clojure
(ns my.bar
  (:require
   [clojure.spec :as s]))

(s/def ::baz any?)
```

`src/my/foo.clj`
```clojure
(ns my.foo
  (:require
   [clojure.spec :as s]
   [my.bar :as bar]))

(s/def ::config (s/keys :req-un [::bar/baz]))
```

### clj-refactor.el and refactor-nrepl version information

clj-refactor 2.2.0, refactor-nrepl 2.2.0

### CIDER version information

```
;; CIDER 0.14.0 (Berlin), nREPL 0.2.12
;; Clojure 1.9.0-alpha13, Java 1.8.0_45
```
### Leiningen or Boot version
```
Leiningen 2.7.1 on Java 1.8.0_45 Java HotSpot(TM) 64-Bit Server VM
```
### Emacs version
```
GNU Emacs 25.1.1 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G1004)) of 2016-11-11
```
### Operating system
```
OS X 10.11 "El Capitan"
```

**Comment by expez** [comment]
Hit <kbd>C-c C-k</kbd> before performing the refactoring, or the namespaces can't be resolved by querying the active REPL.

**Comment by julienfantin** [comment]
@expez thanks I'm aware of this, but this doesn't work for namespaced keywords as reported.

**Comment by expez** [comment]
I didn't notice you were on the last stable.  This is fixed in the latest snapshot release.

**Comment by julienfantin** [comment]
@expez sorry it took me forever to test the latest version. It does mostly work, but I'm still seeing the issue in cljc files

**Comment by benedekfazekas** [comment]
had an other look on this. really frustrating tbh. don't really get what we could do as it seems to me that the reader/compiler just fails on `cljc` files when i try to load them into vanilla jvm REPL containing cljs namespaced keywords. the reader should just ignore those but instead if fails.

tried clojure 1.7, 1.8 and 1.9alpha15 too. no difference. @julienfantin is your use case any different from what i am describing?

**Comment by julienfantin** [comment]
Yes that seems to be issue for me too. Am I understanding this correctly that this problem stems from a different issue, which is that clj-refactor doesn't work on cljc and cljs files?

**Comment by benedekfazekas** [comment]
> Am I understanding this correctly that this problem stems from a different issue, which is that clj-refactor doesn't work on cljc and cljs files?

no, i don't think so. clj-refactor (or more precisely) `refactor-nrepl` can not build ASTs for cljs files. but certain features are implemented with elisp code only (works for all kind of clojure files, example is move to let) *and* more importantly `clean-ns` is an exception in terms of using `refactor-nrepl` but supporting all clojure dialects.

i think the root of the problem here is that the reader/compiler does some weird stuff with aliased clojurescript keywords in cljc files. in fact it should just ignore them when i load a cljc file in a jvm repl but that does seem to be the case.

that is why i am asking what is your cljc usecase exactly? you only want to deal with aliased jvm clojure keywords in cljc files?

**Comment by benedekfazekas** [comment]
btw with latest version `clean-ns` works fine for me for aliased `clj` keywords in `cljc` files. the require for this case does not get removed...

**Comment by benedekfazekas** [comment]
i am inclined to consider this solved. unless this problem (aliased cljs keywords get read in cljc files in jvm clojure) is dealt with upstream we can not do much -- perhaps raise a clojure core jira?!. @julienfantin @expez feel free to reopen if you disagree

**Comment by julienfantin** [comment]
Sorry for the late reply, my use case now seems solved in snapshot. Thanks!
